# ----------------------------------------------------- 
# Autostart
# ----------------------------------------------------- 

exec-once = dbus-update-activation-environment --all

# Setup XDG for screen sharing
exec-once = ~/.config/scripts/xdg-portal.sh

# Start Polkit
# Test Polkit pkexec --user username alacritty
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Load Dunst Notification Manager
exec-once = dunst

exec-once = brightnessctl s 25%

# Load cliphist history
exec-once = wl-paste --watch cliphist store

# Initialize waypaper
# exec-once = hyprpaper
# exec-once = swww-daemon

# Using hypridle to start hyprlock
exec-once = hypridle

exec-once = xhost +local:
