#!/bin/sh

# Start up processes
pgrep -x sxhkd >/dev/null || sxhkd &

# BSPWM config

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 2
bspc config window_gap 6

bspc config normal_border_color "#eceff4"
bspc config focused_border_color "#81A1C1"

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle false

#auto start
numlockx on &
xsetroot -cursor_name left_ptr &
picom --config ~/.config/picom/picom.conf &
feh --bg-fill --randomize ~/Pictures/Wallpapers &
dunst &
# polybar &
xautolock -time 5 -locker "betterlockscreen -l" -killtime 10 -killer "loginctl suspend" -detectsleep &
brightnessctl s 30% &
