#!/bin/sh

# Start up processes
pgrep -x sxhkd >/dev/null || (sxhkd &)
# pgrep -x pipewire >/dev/null || (pipewire &)

# BSPWM config
# bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#### BSPWM configuration ####
#bspc config border_radius
bspc config single_monocle true
bspc config click_to_focus true
bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config focus_by_distance true
bspc config focus_follows_pointer true
bspc config history_aware_focus true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config border_width 2
bspc config window_gap 8

#### BSPWM coloring ####
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#5e81ac"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"

# Auto start applications
{
  numlockx on &
  xsetroot -cursor_name left_ptr &
  picom --config ~/.config/picom/picom.conf &
  # feh --bg-fill --randomize ~/Pictures/Wallpapers &
  dunst &
  brightnessctl s 20% &
  /usr/libexec/hyprpolkitagent &
  ~/.config/scripts/xautolock.sh &
  ~/.config/scripts/check_init_pipewire.sh &
  ~/.config/scripts/x11_dual_monitor.sh &
  # ~/.config/scripts/check_xautolock.sh &
} &

wait
