return {
	{
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
		config = function()
			local config = require("nvim-treesitter.configs")
			config.setup({
				-- Automatically install missing parsers
				auto_install = true,
				-- Enable syntax highlighting
				highlight = { enable = true },
				-- Enable indentation based on treesitter
				ignore_install = {},
				indent = { enable = true },
				sync_install = true,
				modules = {},
				-- Ensure these parsers are installed
				ensure_installed = {
					"bash",
					"c",
					"cpp",
					"kotlin",
					"c_sharp",
					"java",
					"diff",
					"fish",
					"jsdoc",
					"jsonc",
					"luadoc",
					"luap",
					"python",
					"regex",
					"svelte",
					"go",
					"gomod",
					"gowork",
					"gosum",
					"toml",
					"vimdoc",
					"yaml",
					"vue",
					"astro",
					"json",
					"javascript",
					"typescript",
					"tsx",
					"html",
					"css",
					"xml",
					"prisma",
					"markdown",
					"http",
					"markdown_inline",
					"sql",
					"graphql",
					"lua",
					"vim",
					"dockerfile",
					"gitignore",
					"query",
					"php",
					"angular",
					"dart",
					"blade",
					"php_only",
				},
			})
		end,
	},
}
